# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 515fdd1e740a577ee3c2564cdf9817038c5f4d3e684ad21158e4bec8bd515e74ed8fb5b5e823616653b0685f54e97bf6a5b651fa165b314fb8c4d9aecdf562b2

test:
  secret_key_base: dfb1375a0bc394d71ca7dba3031d9e44e863276372a543a1872a0b59f02922320cacf6c787bf74d7b9194095c666f810786ec1adb701e955a886490a4e7107dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
